---
- name: Install common packages
  yum:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Update packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
