- name: Build and upload WAR file from bastion host
  hosts: bastion
  become: true
  vars:
    repo_url: "https://github.com/omaromarsalhi/DevOps-Projects.git"
    repo_dest: "/home/ec2-user"
    java_repo_name: "Java-Login-App"
    war_name: "dptweb-1.0.war"
    s3_bucket: "my-artifacts-java"
  tasks:
    - name: Show repo_dest
      debug:
        var: repo_dest

    - name: Ensure git and maven are installed
      yum:
        name:
          - git
          - maven
        state: present

    - name: Create repo_dest parent directory
      file:
        path: "{{ repo_dest | dirname }}"
        state: directory
        mode: "0755"

    - name: Clone the monorepo with depth 1
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest | dirname }}/repo_tmp"
        version: master
        depth: 1
        single_branch: yes
        force: yes

    - name: Enable sparse-checkout
      command: git sparse-checkout init --cone
      args:
        chdir: "{{ repo_dest | dirname }}/repo_tmp"

    - name: Set sparse-checkout to only Java-Login-App
      command: git sparse-checkout set DevOps-Project-01/Java-Login-App
      args:
        chdir: "{{ repo_dest | dirname }}/repo_tmp"

    - name: Remove existing Java-Login-App directory if present
      file:
        path: "{{ repo_dest }}/{{ java_repo_name }}"
        state: absent

    - name: Move Java-Login-App to repo_dest
      command: mv {{ repo_dest | dirname }}/repo_tmp/DevOps-Project-01/{{ java_repo_name }} {{ repo_dest }}/{{ java_repo_name }}

    - name: Remove temporary repo_tmp directory
      file:
        path: "{{ repo_dest | dirname }}/repo_tmp"
        state: absent

    - name: Build the WAR file with Maven
      command: mvn clean package
      args:
        chdir: "{{ repo_dest }}/{{ java_repo_name }}"

    - name: Upload WAR file to S3
      aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ war_name }}"
        src: "{{ repo_dest }}/{{ java_repo_name }}/target/{{ war_name }}"
        mode: put
      become: false
