---
- import_playbook: install-tomcat.yml
- import_playbook: install-nginx.yml

- name: Final verification
  hosts: all
  become: yes
  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
      register: nginx_status
      when: inventory_hostname in groups['webservers']

    - name: Check Tomcat status
      systemd:
        name: tomcat
      register: tomcat_status
      when: inventory_hostname in groups['appservers']

    - name: Display status
      debug:
        msg: |
          Server: {{ inventory_hostname }}
          {% if inventory_hostname in groups['webservers'] %}
          Nginx: {{ nginx_status.status.ActiveState }}
          {% endif %}
          {% if inventory_hostname in groups['appservers'] %}
          Tomcat: {{ tomcat_status.status.ActiveState }}
          {% endif %}
