---
- name: Install and configure Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Backup original nginx.conf
      copy:
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf.backup
        remote_src: yes
        backup: yes

    - name: Configure Nginx as reverse proxy
      copy:
        content: |
          upstream app_servers {
              server {{ hostvars[groups['appservers'][0]]['ansible_host'] }}:8080 max_fails=3 fail_timeout=30s;
              server {{ hostvars[groups['appservers'][1]]['ansible_host'] }}:8080 max_fails=3 fail_timeout=30s;
          }
          
          server {
              listen 80;
              server_name _;
              
              location /health {
                  access_log off;
                  return 200 "healthy\n";
                  add_header Content-Type text/plain;
              }
              
              location / {
                  proxy_pass http://app_servers;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_connect_timeout 30;
                  proxy_send_timeout 30;
                  proxy_read_timeout 30;
                  proxy_buffering off;
              }
          }
        dest: /etc/nginx/conf.d/app.conf

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
