---
- name: Install and configure Tomcat
  hosts: appservers
  become: yes
  vars:
    tomcat_version: "{{ tomcat_version }}"
    java_home: "{{ java_home }}"
    tomcat_user: "{{ tomcat_user }}"
    tomcat_group: "{{ tomcat_group }}"
    tomcat_home: "{{ tomcat_home }}"
    
  tasks:
    - name: Install Java 11 and required packages
      yum:
        name:
          - java-11-openjdk-devel
          - wget
          - tar
        state: present

    - name: Create tomcat group
      group:
        name: "{{ tomcat_group }}"
        system: yes

    - name: Create tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        system: yes
        shell: /bin/false
        home: "{{ tomcat_home }}"
        createhome: no

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: '0644'

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt
        remote_src: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        creates: "/opt/apache-tomcat-{{ tomcat_version }}"

    - name: Create symlink for Tomcat
      file:
        src: "/opt/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_home }}"
        state: link
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        force: yes

    - name: Set permissions on Tomcat directories
      file:
        path: "{{ item }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'
        recurse: yes
      loop:
        - "{{ tomcat_home }}/bin"
        - "{{ tomcat_home }}/conf"
        - "{{ tomcat_home }}/webapps"
        - "{{ tomcat_home }}/work"
        - "{{ tomcat_home }}/temp"
        - "{{ tomcat_home }}/logs"

    - name: Create Tomcat systemd service
      copy:
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          Environment=JAVA_HOME={{ java_home }}
          Environment=CATALINA_PID={{ tomcat_home }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_home }}
          Environment=CATALINA_BASE={{ tomcat_home }}
          Environment='CATALINA_OPTS=-Xms{{ tomcat_memory_min }} -Xmx{{ tomcat_memory_max }} -server -XX:+UseParallelGC'
          ExecStart={{ tomcat_home }}/bin/startup.sh
          ExecStop={{ tomcat_home }}/bin/shutdown.sh
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service

    - name: Start and enable Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Tomcat to start
      wait_for:
        port: "{{ tomcat_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60
