---
- name: Setup S3 bucket for application artifacts
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    bucket_name: "devops-project-artifacts-{{ ansible_date_time.epoch }}"
    aws_region: "{{ aws_region }}"
    
  tasks:
    - name: Create S3 bucket for artifacts
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ aws_region }}"
        state: present
        public_access:
          block_public_acls: true
          block_public_policy: true
          ignore_public_acls: true
          restrict_public_buckets: true
      register: s3_bucket

    - name: Enable S3 bucket versioning
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        versioning: yes
        region: "{{ aws_region }}"

    - name: Display bucket information
      debug:
        msg: |
          S3 Bucket Created: {{ bucket_name }}
          Region: {{ aws_region }}

    - name: Save bucket name to file
      copy:
        content: |
          S3_BUCKET_NAME={{ bucket_name }}
          S3_REGION={{ aws_region }}
        dest: s3-config.env
