---
- name: Install Java and Tomcat on app servers
  hosts: appservers
  become: true
  gather_facts: true

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/appservers.yml
  
  tasks:
    - name: Install Java (Amazon Corretto 17)
      dnf:
        name: "{{ java_package }}"
        state: present

    - name: Create tomcat group
      group:
        name: tomcat
        state: present

    - name: Create tomcat user
      user:
        name: tomcat
        group: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false
        system: true
        state: present

    - name: Get latest Tomcat 9 version from Apache
      uri:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/
        return_content: true
      register: tomcat9_page

    - name: Extract latest Tomcat 9 version number
      set_fact:
        tomcat_version: "{{ tomcat9_page.content | regex_findall('v[0-9]+\\.[0-9]+\\.[0-9]+') | sort | last | regex_replace('^v','') }}"

    - name: Check if Tomcat is already installed
      stat:
        path: "{{ tomcat_install_dir }}/bin/catalina.sh"
      register: tomcat_installed

    - name: Download Tomcat {{ tomcat_version }}
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        timeout: 60
      when: not tomcat_installed.stat.exists

    - name: Extract Tomcat to /opt
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt/
        remote_src: true
        creates: "/opt/apache-tomcat-{{ tomcat_version }}"
      when: not tomcat_installed.stat.exists

    - name: Remove existing Tomcat symlink if present
      file:
        path: "{{ tomcat_install_dir }}"
        state: absent
      when: not tomcat_installed.stat.exists

    - name: Create symlink for Tomcat
      file:
        src: "/opt/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_install_dir }}"
        state: link
        force: true
      when: not tomcat_installed.stat.exists

    - name: Set ownership of actual Tomcat directory
      file:
        path: "/opt/apache-tomcat-{{ tomcat_version }}"
        owner: tomcat
        group: tomcat
        recurse: true
        state: directory
      when: not tomcat_installed.stat.exists

    - name: Set ownership of symlink
      file:
        path: "{{ tomcat_install_dir }}"
        owner: tomcat
        group: tomcat
        state: link
      when: not tomcat_installed.stat.exists

    - name: Stop Tomcat if running (before service creation)
      systemd:
        name: tomcat
        state: stopped
      failed_when: false
      ignore_errors: true

    - name: Create Tomcat systemd service
      template:
        src: ../templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
        mode: '0644'
      notify:
        - Reload systemd
        - Restart tomcat

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Ensure Tomcat scripts are executable
      file:
        path: "{{ tomcat_install_dir }}/bin/{{ item }}"
        mode: '0755'
        owner: tomcat
        group: tomcat
      loop:
        - catalina.sh
        - startup.sh
        - shutdown.sh

    - name: Ensure Tomcat directories have proper permissions
      file:
        path: "{{ tomcat_install_dir }}/{{ item }}"
        owner: tomcat
        group: tomcat
        state: directory
        recurse: true
      loop:
        - logs
        - temp
        - work
        - webapps

    - name: Create temp directory if it doesn't exist
      file:
        path: "{{ tomcat_install_dir }}/temp"
        owner: tomcat
        group: tomcat
        state: directory
        mode: '0755'

    - name: Remove any stale PID files
      file:
        path: "{{ tomcat_install_dir }}/temp/tomcat.pid"
        state: absent

    - name: Start and enable Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: true

    # Enhanced troubleshooting before waiting
    - name: Check Tomcat service status
      systemd:
        name: tomcat
      register: tomcat_status

    - name: Debug - Show service status
      debug:
        var: tomcat_status

    - name: Check Tomcat logs for errors
      command: journalctl -u tomcat -n 20 --no-pager
      register: tomcat_logs
      changed_when: false

    - name: Debug - Show recent Tomcat logs
      debug:
        var: tomcat_logs.stdout_lines

    - name: Wait for Tomcat to start (shorter timeout for debugging)
      wait_for:
        port: 8080
        host: 0.0.0.0
        delay: 10
        timeout: 45
      register: port_check
      failed_when: false

    - name: Debug - Port check result
      debug:
        var: port_check

    - name: Check what's listening on port 8080
      command: netstat -tlnp | grep 8080
      register: port_listen
      failed_when: false
      changed_when: false

    - name: Debug - Port listening status
      debug:
        var: port_listen.stdout_lines

    - name: Verify Tomcat is running (if port is available)
      uri:
        url: "http://localhost:8080"
        method: GET
        status_code: 200
      retries: 3
      delay: 5
      when: port_check.elapsed is defined and port_check.elapsed < 45

    - name: Clean up downloaded archive
      file:
        path: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        state: absent

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: true
    
    - name: Restart tomcat
      systemd:
        name: tomcat
        state: restarted