---
- name: Install Java
  yum:
    name: java-11-openjdk-devel
    state: present

- name: Create tomcat user
  user:
    name: "{{ tomcat_user }}"
    system: yes
    shell: /bin/false
    home: "{{ tomcat_home }}"
    createhome: no

- name: Download and extract Tomcat
  unarchive:
    src: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    creates: "/opt/apache-tomcat-{{ tomcat_version }}"

- name: Create symlink
  file:
    src: "/opt/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_home }}"
    state: link
